//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTester.HeresyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HeresyService.IHeresyService")]
    public interface IHeresyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetCharacterDescriptionList", ReplyAction="http://tempuri.org/IHeresyService/GetCharacterDescriptionListResponse")]
        System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.CharacterDescription> GetCharacterDescriptionList(HeresyCore.Entities.Token token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetCharacterDescriptionList", ReplyAction="http://tempuri.org/IHeresyService/GetCharacterDescriptionListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.CharacterDescription>> GetCharacterDescriptionListAsync(HeresyCore.Entities.Token token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetCharacterDescription", ReplyAction="http://tempuri.org/IHeresyService/GetCharacterDescriptionResponse")]
        HeresyCore.Descriptions.CharacterDescription GetCharacterDescription(HeresyCore.Entities.Token token, string charId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetCharacterDescription", ReplyAction="http://tempuri.org/IHeresyService/GetCharacterDescriptionResponse")]
        System.Threading.Tasks.Task<HeresyCore.Descriptions.CharacterDescription> GetCharacterDescriptionAsync(HeresyCore.Entities.Token token, string charId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetWorldDescriptions", ReplyAction="http://tempuri.org/IHeresyService/GetWorldDescriptionsResponse")]
        System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.WorldDescription> GetWorldDescriptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetWorldDescriptions", ReplyAction="http://tempuri.org/IHeresyService/GetWorldDescriptionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.WorldDescription>> GetWorldDescriptionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetWorldDescription", ReplyAction="http://tempuri.org/IHeresyService/GetWorldDescriptionResponse")]
        HeresyCore.Descriptions.WorldDescription GetWorldDescription(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetWorldDescription", ReplyAction="http://tempuri.org/IHeresyService/GetWorldDescriptionResponse")]
        System.Threading.Tasks.Task<HeresyCore.Descriptions.WorldDescription> GetWorldDescriptionAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/TryGetWorldDescription", ReplyAction="http://tempuri.org/IHeresyService/TryGetWorldDescriptionResponse")]
        ServiceTester.HeresyService.TryGetWorldDescriptionResponse TryGetWorldDescription(ServiceTester.HeresyService.TryGetWorldDescriptionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/TryGetWorldDescription", ReplyAction="http://tempuri.org/IHeresyService/TryGetWorldDescriptionResponse")]
        System.Threading.Tasks.Task<ServiceTester.HeresyService.TryGetWorldDescriptionResponse> TryGetWorldDescriptionAsync(ServiceTester.HeresyService.TryGetWorldDescriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetRaceDescriptions", ReplyAction="http://tempuri.org/IHeresyService/GetRaceDescriptionsResponse")]
        System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.RaceDescription> GetRaceDescriptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetRaceDescriptions", ReplyAction="http://tempuri.org/IHeresyService/GetRaceDescriptionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.RaceDescription>> GetRaceDescriptionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetRaceDescription", ReplyAction="http://tempuri.org/IHeresyService/GetRaceDescriptionResponse")]
        HeresyCore.Descriptions.RaceDescription GetRaceDescription(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetRaceDescription", ReplyAction="http://tempuri.org/IHeresyService/GetRaceDescriptionResponse")]
        System.Threading.Tasks.Task<HeresyCore.Descriptions.RaceDescription> GetRaceDescriptionAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/TryGetRaceDescription", ReplyAction="http://tempuri.org/IHeresyService/TryGetRaceDescriptionResponse")]
        ServiceTester.HeresyService.TryGetRaceDescriptionResponse TryGetRaceDescription(ServiceTester.HeresyService.TryGetRaceDescriptionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/TryGetRaceDescription", ReplyAction="http://tempuri.org/IHeresyService/TryGetRaceDescriptionResponse")]
        System.Threading.Tasks.Task<ServiceTester.HeresyService.TryGetRaceDescriptionResponse> TryGetRaceDescriptionAsync(ServiceTester.HeresyService.TryGetRaceDescriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetClassDescriptions", ReplyAction="http://tempuri.org/IHeresyService/GetClassDescriptionsResponse")]
        System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.ClassDescription> GetClassDescriptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetClassDescriptions", ReplyAction="http://tempuri.org/IHeresyService/GetClassDescriptionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.ClassDescription>> GetClassDescriptionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetClassDescription", ReplyAction="http://tempuri.org/IHeresyService/GetClassDescriptionResponse")]
        HeresyCore.Descriptions.ClassDescription GetClassDescription(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetClassDescription", ReplyAction="http://tempuri.org/IHeresyService/GetClassDescriptionResponse")]
        System.Threading.Tasks.Task<HeresyCore.Descriptions.ClassDescription> GetClassDescriptionAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/TryGetClassDescription", ReplyAction="http://tempuri.org/IHeresyService/TryGetClassDescriptionResponse")]
        ServiceTester.HeresyService.TryGetClassDescriptionResponse TryGetClassDescription(ServiceTester.HeresyService.TryGetClassDescriptionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/TryGetClassDescription", ReplyAction="http://tempuri.org/IHeresyService/TryGetClassDescriptionResponse")]
        System.Threading.Tasks.Task<ServiceTester.HeresyService.TryGetClassDescriptionResponse> TryGetClassDescriptionAsync(ServiceTester.HeresyService.TryGetClassDescriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetBackgroundDescriptions", ReplyAction="http://tempuri.org/IHeresyService/GetBackgroundDescriptionsResponse")]
        System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.BackgroundDescription> GetBackgroundDescriptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetBackgroundDescriptions", ReplyAction="http://tempuri.org/IHeresyService/GetBackgroundDescriptionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.BackgroundDescription>> GetBackgroundDescriptionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetBackgroundDescription", ReplyAction="http://tempuri.org/IHeresyService/GetBackgroundDescriptionResponse")]
        HeresyCore.Descriptions.BackgroundDescription GetBackgroundDescription(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/GetBackgroundDescription", ReplyAction="http://tempuri.org/IHeresyService/GetBackgroundDescriptionResponse")]
        System.Threading.Tasks.Task<HeresyCore.Descriptions.BackgroundDescription> GetBackgroundDescriptionAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/TryGetBackgroundDescription", ReplyAction="http://tempuri.org/IHeresyService/TryGetBackgroundDescriptionResponse")]
        ServiceTester.HeresyService.TryGetBackgroundDescriptionResponse TryGetBackgroundDescription(ServiceTester.HeresyService.TryGetBackgroundDescriptionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/TryGetBackgroundDescription", ReplyAction="http://tempuri.org/IHeresyService/TryGetBackgroundDescriptionResponse")]
        System.Threading.Tasks.Task<ServiceTester.HeresyService.TryGetBackgroundDescriptionResponse> TryGetBackgroundDescriptionAsync(ServiceTester.HeresyService.TryGetBackgroundDescriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/CreateCharacter", ReplyAction="http://tempuri.org/IHeresyService/CreateCharacterResponse")]
        string CreateCharacter(HeresyCore.Entities.Token token, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/CreateCharacter", ReplyAction="http://tempuri.org/IHeresyService/CreateCharacterResponse")]
        System.Threading.Tasks.Task<string> CreateCharacterAsync(HeresyCore.Entities.Token token, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SelectRace", ReplyAction="http://tempuri.org/IHeresyService/SelectRaceResponse")]
        bool SelectRace(HeresyCore.Entities.Token token, string charId, string raceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SelectRace", ReplyAction="http://tempuri.org/IHeresyService/SelectRaceResponse")]
        System.Threading.Tasks.Task<bool> SelectRaceAsync(HeresyCore.Entities.Token token, string charId, string raceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/RerollStat", ReplyAction="http://tempuri.org/IHeresyService/RerollStatResponse")]
        bool RerollStat(HeresyCore.Entities.Token token, string charId, HeresyCore.Entities.Enums.ECharacterStat stat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/RerollStat", ReplyAction="http://tempuri.org/IHeresyService/RerollStatResponse")]
        System.Threading.Tasks.Task<bool> RerollStatAsync(HeresyCore.Entities.Token token, string charId, HeresyCore.Entities.Enums.ECharacterStat stat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SkipReroll", ReplyAction="http://tempuri.org/IHeresyService/SkipRerollResponse")]
        bool SkipReroll(HeresyCore.Entities.Token token, string charId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SkipReroll", ReplyAction="http://tempuri.org/IHeresyService/SkipRerollResponse")]
        System.Threading.Tasks.Task<bool> SkipRerollAsync(HeresyCore.Entities.Token token, string charId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SelectWorld", ReplyAction="http://tempuri.org/IHeresyService/SelectWorldResponse")]
        bool SelectWorld(HeresyCore.Entities.Token token, string charId, string worldId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SelectWorld", ReplyAction="http://tempuri.org/IHeresyService/SelectWorldResponse")]
        System.Threading.Tasks.Task<bool> SelectWorldAsync(HeresyCore.Entities.Token token, string charId, string worldId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SelectClass", ReplyAction="http://tempuri.org/IHeresyService/SelectClassResponse")]
        bool SelectClass(HeresyCore.Entities.Token token, string charId, string classId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SelectClass", ReplyAction="http://tempuri.org/IHeresyService/SelectClassResponse")]
        System.Threading.Tasks.Task<bool> SelectClassAsync(HeresyCore.Entities.Token token, string charId, string classId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SelectBackground", ReplyAction="http://tempuri.org/IHeresyService/SelectBackgroundResponse")]
        bool SelectBackground(HeresyCore.Entities.Token token, string charId, string backgroundId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SelectBackground", ReplyAction="http://tempuri.org/IHeresyService/SelectBackgroundResponse")]
        System.Threading.Tasks.Task<bool> SelectBackgroundAsync(HeresyCore.Entities.Token token, string charId, string backgroundId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SkipBackground", ReplyAction="http://tempuri.org/IHeresyService/SkipBackgroundResponse")]
        bool SkipBackground(HeresyCore.Entities.Token token, string charId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SkipBackground", ReplyAction="http://tempuri.org/IHeresyService/SkipBackgroundResponse")]
        System.Threading.Tasks.Task<bool> SkipBackgroundAsync(HeresyCore.Entities.Token token, string charId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SelectFreebie", ReplyAction="http://tempuri.org/IHeresyService/SelectFreebieResponse")]
        bool SelectFreebie(HeresyCore.Entities.Token token, string charId, int freebieId, int optionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/SelectFreebie", ReplyAction="http://tempuri.org/IHeresyService/SelectFreebieResponse")]
        System.Threading.Tasks.Task<bool> SelectFreebieAsync(HeresyCore.Entities.Token token, string charId, int freebieId, int optionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/UpgradeStat", ReplyAction="http://tempuri.org/IHeresyService/UpgradeStatResponse")]
        bool UpgradeStat(HeresyCore.Entities.Token token, string charId, HeresyCore.Entities.Enums.ECharacterStat stat, int points);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeresyService/UpgradeStat", ReplyAction="http://tempuri.org/IHeresyService/UpgradeStatResponse")]
        System.Threading.Tasks.Task<bool> UpgradeStatAsync(HeresyCore.Entities.Token token, string charId, HeresyCore.Entities.Enums.ECharacterStat stat, int points);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TryGetWorldDescription", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TryGetWorldDescriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        public TryGetWorldDescriptionRequest() {
        }
        
        public TryGetWorldDescriptionRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TryGetWorldDescriptionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TryGetWorldDescriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool TryGetWorldDescriptionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public HeresyCore.Descriptions.WorldDescription world;
        
        public TryGetWorldDescriptionResponse() {
        }
        
        public TryGetWorldDescriptionResponse(bool TryGetWorldDescriptionResult, HeresyCore.Descriptions.WorldDescription world) {
            this.TryGetWorldDescriptionResult = TryGetWorldDescriptionResult;
            this.world = world;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TryGetRaceDescription", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TryGetRaceDescriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        public TryGetRaceDescriptionRequest() {
        }
        
        public TryGetRaceDescriptionRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TryGetRaceDescriptionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TryGetRaceDescriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool TryGetRaceDescriptionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public HeresyCore.Descriptions.RaceDescription race;
        
        public TryGetRaceDescriptionResponse() {
        }
        
        public TryGetRaceDescriptionResponse(bool TryGetRaceDescriptionResult, HeresyCore.Descriptions.RaceDescription race) {
            this.TryGetRaceDescriptionResult = TryGetRaceDescriptionResult;
            this.race = race;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TryGetClassDescription", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TryGetClassDescriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        public TryGetClassDescriptionRequest() {
        }
        
        public TryGetClassDescriptionRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TryGetClassDescriptionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TryGetClassDescriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool TryGetClassDescriptionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public HeresyCore.Descriptions.ClassDescription c;
        
        public TryGetClassDescriptionResponse() {
        }
        
        public TryGetClassDescriptionResponse(bool TryGetClassDescriptionResult, HeresyCore.Descriptions.ClassDescription c) {
            this.TryGetClassDescriptionResult = TryGetClassDescriptionResult;
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TryGetBackgroundDescription", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TryGetBackgroundDescriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        public TryGetBackgroundDescriptionRequest() {
        }
        
        public TryGetBackgroundDescriptionRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TryGetBackgroundDescriptionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TryGetBackgroundDescriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool TryGetBackgroundDescriptionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public HeresyCore.Descriptions.BackgroundDescription c;
        
        public TryGetBackgroundDescriptionResponse() {
        }
        
        public TryGetBackgroundDescriptionResponse(bool TryGetBackgroundDescriptionResult, HeresyCore.Descriptions.BackgroundDescription c) {
            this.TryGetBackgroundDescriptionResult = TryGetBackgroundDescriptionResult;
            this.c = c;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeresyServiceChannel : ServiceTester.HeresyService.IHeresyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeresyServiceClient : System.ServiceModel.ClientBase<ServiceTester.HeresyService.IHeresyService>, ServiceTester.HeresyService.IHeresyService {
        
        public HeresyServiceClient() {
        }
        
        public HeresyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HeresyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeresyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeresyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.CharacterDescription> GetCharacterDescriptionList(HeresyCore.Entities.Token token) {
            return base.Channel.GetCharacterDescriptionList(token);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.CharacterDescription>> GetCharacterDescriptionListAsync(HeresyCore.Entities.Token token) {
            return base.Channel.GetCharacterDescriptionListAsync(token);
        }
        
        public HeresyCore.Descriptions.CharacterDescription GetCharacterDescription(HeresyCore.Entities.Token token, string charId) {
            return base.Channel.GetCharacterDescription(token, charId);
        }
        
        public System.Threading.Tasks.Task<HeresyCore.Descriptions.CharacterDescription> GetCharacterDescriptionAsync(HeresyCore.Entities.Token token, string charId) {
            return base.Channel.GetCharacterDescriptionAsync(token, charId);
        }
        
        public System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.WorldDescription> GetWorldDescriptions() {
            return base.Channel.GetWorldDescriptions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.WorldDescription>> GetWorldDescriptionsAsync() {
            return base.Channel.GetWorldDescriptionsAsync();
        }
        
        public HeresyCore.Descriptions.WorldDescription GetWorldDescription(string id) {
            return base.Channel.GetWorldDescription(id);
        }
        
        public System.Threading.Tasks.Task<HeresyCore.Descriptions.WorldDescription> GetWorldDescriptionAsync(string id) {
            return base.Channel.GetWorldDescriptionAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTester.HeresyService.TryGetWorldDescriptionResponse ServiceTester.HeresyService.IHeresyService.TryGetWorldDescription(ServiceTester.HeresyService.TryGetWorldDescriptionRequest request) {
            return base.Channel.TryGetWorldDescription(request);
        }
        
        public bool TryGetWorldDescription(string id, out HeresyCore.Descriptions.WorldDescription world) {
            ServiceTester.HeresyService.TryGetWorldDescriptionRequest inValue = new ServiceTester.HeresyService.TryGetWorldDescriptionRequest();
            inValue.id = id;
            ServiceTester.HeresyService.TryGetWorldDescriptionResponse retVal = ((ServiceTester.HeresyService.IHeresyService)(this)).TryGetWorldDescription(inValue);
            world = retVal.world;
            return retVal.TryGetWorldDescriptionResult;
        }
        
        public System.Threading.Tasks.Task<ServiceTester.HeresyService.TryGetWorldDescriptionResponse> TryGetWorldDescriptionAsync(ServiceTester.HeresyService.TryGetWorldDescriptionRequest request) {
            return base.Channel.TryGetWorldDescriptionAsync(request);
        }
        
        public System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.RaceDescription> GetRaceDescriptions() {
            return base.Channel.GetRaceDescriptions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.RaceDescription>> GetRaceDescriptionsAsync() {
            return base.Channel.GetRaceDescriptionsAsync();
        }
        
        public HeresyCore.Descriptions.RaceDescription GetRaceDescription(string id) {
            return base.Channel.GetRaceDescription(id);
        }
        
        public System.Threading.Tasks.Task<HeresyCore.Descriptions.RaceDescription> GetRaceDescriptionAsync(string id) {
            return base.Channel.GetRaceDescriptionAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTester.HeresyService.TryGetRaceDescriptionResponse ServiceTester.HeresyService.IHeresyService.TryGetRaceDescription(ServiceTester.HeresyService.TryGetRaceDescriptionRequest request) {
            return base.Channel.TryGetRaceDescription(request);
        }
        
        public bool TryGetRaceDescription(string id, out HeresyCore.Descriptions.RaceDescription race) {
            ServiceTester.HeresyService.TryGetRaceDescriptionRequest inValue = new ServiceTester.HeresyService.TryGetRaceDescriptionRequest();
            inValue.id = id;
            ServiceTester.HeresyService.TryGetRaceDescriptionResponse retVal = ((ServiceTester.HeresyService.IHeresyService)(this)).TryGetRaceDescription(inValue);
            race = retVal.race;
            return retVal.TryGetRaceDescriptionResult;
        }
        
        public System.Threading.Tasks.Task<ServiceTester.HeresyService.TryGetRaceDescriptionResponse> TryGetRaceDescriptionAsync(ServiceTester.HeresyService.TryGetRaceDescriptionRequest request) {
            return base.Channel.TryGetRaceDescriptionAsync(request);
        }
        
        public System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.ClassDescription> GetClassDescriptions() {
            return base.Channel.GetClassDescriptions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.ClassDescription>> GetClassDescriptionsAsync() {
            return base.Channel.GetClassDescriptionsAsync();
        }
        
        public HeresyCore.Descriptions.ClassDescription GetClassDescription(string id) {
            return base.Channel.GetClassDescription(id);
        }
        
        public System.Threading.Tasks.Task<HeresyCore.Descriptions.ClassDescription> GetClassDescriptionAsync(string id) {
            return base.Channel.GetClassDescriptionAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTester.HeresyService.TryGetClassDescriptionResponse ServiceTester.HeresyService.IHeresyService.TryGetClassDescription(ServiceTester.HeresyService.TryGetClassDescriptionRequest request) {
            return base.Channel.TryGetClassDescription(request);
        }
        
        public bool TryGetClassDescription(string id, out HeresyCore.Descriptions.ClassDescription c) {
            ServiceTester.HeresyService.TryGetClassDescriptionRequest inValue = new ServiceTester.HeresyService.TryGetClassDescriptionRequest();
            inValue.id = id;
            ServiceTester.HeresyService.TryGetClassDescriptionResponse retVal = ((ServiceTester.HeresyService.IHeresyService)(this)).TryGetClassDescription(inValue);
            c = retVal.c;
            return retVal.TryGetClassDescriptionResult;
        }
        
        public System.Threading.Tasks.Task<ServiceTester.HeresyService.TryGetClassDescriptionResponse> TryGetClassDescriptionAsync(ServiceTester.HeresyService.TryGetClassDescriptionRequest request) {
            return base.Channel.TryGetClassDescriptionAsync(request);
        }
        
        public System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.BackgroundDescription> GetBackgroundDescriptions() {
            return base.Channel.GetBackgroundDescriptions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, HeresyCore.Descriptions.BackgroundDescription>> GetBackgroundDescriptionsAsync() {
            return base.Channel.GetBackgroundDescriptionsAsync();
        }
        
        public HeresyCore.Descriptions.BackgroundDescription GetBackgroundDescription(string id) {
            return base.Channel.GetBackgroundDescription(id);
        }
        
        public System.Threading.Tasks.Task<HeresyCore.Descriptions.BackgroundDescription> GetBackgroundDescriptionAsync(string id) {
            return base.Channel.GetBackgroundDescriptionAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTester.HeresyService.TryGetBackgroundDescriptionResponse ServiceTester.HeresyService.IHeresyService.TryGetBackgroundDescription(ServiceTester.HeresyService.TryGetBackgroundDescriptionRequest request) {
            return base.Channel.TryGetBackgroundDescription(request);
        }
        
        public bool TryGetBackgroundDescription(string id, out HeresyCore.Descriptions.BackgroundDescription c) {
            ServiceTester.HeresyService.TryGetBackgroundDescriptionRequest inValue = new ServiceTester.HeresyService.TryGetBackgroundDescriptionRequest();
            inValue.id = id;
            ServiceTester.HeresyService.TryGetBackgroundDescriptionResponse retVal = ((ServiceTester.HeresyService.IHeresyService)(this)).TryGetBackgroundDescription(inValue);
            c = retVal.c;
            return retVal.TryGetBackgroundDescriptionResult;
        }
        
        public System.Threading.Tasks.Task<ServiceTester.HeresyService.TryGetBackgroundDescriptionResponse> TryGetBackgroundDescriptionAsync(ServiceTester.HeresyService.TryGetBackgroundDescriptionRequest request) {
            return base.Channel.TryGetBackgroundDescriptionAsync(request);
        }
        
        public string CreateCharacter(HeresyCore.Entities.Token token, string name) {
            return base.Channel.CreateCharacter(token, name);
        }
        
        public System.Threading.Tasks.Task<string> CreateCharacterAsync(HeresyCore.Entities.Token token, string name) {
            return base.Channel.CreateCharacterAsync(token, name);
        }
        
        public bool SelectRace(HeresyCore.Entities.Token token, string charId, string raceId) {
            return base.Channel.SelectRace(token, charId, raceId);
        }
        
        public System.Threading.Tasks.Task<bool> SelectRaceAsync(HeresyCore.Entities.Token token, string charId, string raceId) {
            return base.Channel.SelectRaceAsync(token, charId, raceId);
        }
        
        public bool RerollStat(HeresyCore.Entities.Token token, string charId, HeresyCore.Entities.Enums.ECharacterStat stat) {
            return base.Channel.RerollStat(token, charId, stat);
        }
        
        public System.Threading.Tasks.Task<bool> RerollStatAsync(HeresyCore.Entities.Token token, string charId, HeresyCore.Entities.Enums.ECharacterStat stat) {
            return base.Channel.RerollStatAsync(token, charId, stat);
        }
        
        public bool SkipReroll(HeresyCore.Entities.Token token, string charId) {
            return base.Channel.SkipReroll(token, charId);
        }
        
        public System.Threading.Tasks.Task<bool> SkipRerollAsync(HeresyCore.Entities.Token token, string charId) {
            return base.Channel.SkipRerollAsync(token, charId);
        }
        
        public bool SelectWorld(HeresyCore.Entities.Token token, string charId, string worldId) {
            return base.Channel.SelectWorld(token, charId, worldId);
        }
        
        public System.Threading.Tasks.Task<bool> SelectWorldAsync(HeresyCore.Entities.Token token, string charId, string worldId) {
            return base.Channel.SelectWorldAsync(token, charId, worldId);
        }
        
        public bool SelectClass(HeresyCore.Entities.Token token, string charId, string classId) {
            return base.Channel.SelectClass(token, charId, classId);
        }
        
        public System.Threading.Tasks.Task<bool> SelectClassAsync(HeresyCore.Entities.Token token, string charId, string classId) {
            return base.Channel.SelectClassAsync(token, charId, classId);
        }
        
        public bool SelectBackground(HeresyCore.Entities.Token token, string charId, string backgroundId) {
            return base.Channel.SelectBackground(token, charId, backgroundId);
        }
        
        public System.Threading.Tasks.Task<bool> SelectBackgroundAsync(HeresyCore.Entities.Token token, string charId, string backgroundId) {
            return base.Channel.SelectBackgroundAsync(token, charId, backgroundId);
        }
        
        public bool SkipBackground(HeresyCore.Entities.Token token, string charId) {
            return base.Channel.SkipBackground(token, charId);
        }
        
        public System.Threading.Tasks.Task<bool> SkipBackgroundAsync(HeresyCore.Entities.Token token, string charId) {
            return base.Channel.SkipBackgroundAsync(token, charId);
        }
        
        public bool SelectFreebie(HeresyCore.Entities.Token token, string charId, int freebieId, int optionId) {
            return base.Channel.SelectFreebie(token, charId, freebieId, optionId);
        }
        
        public System.Threading.Tasks.Task<bool> SelectFreebieAsync(HeresyCore.Entities.Token token, string charId, int freebieId, int optionId) {
            return base.Channel.SelectFreebieAsync(token, charId, freebieId, optionId);
        }
        
        public bool UpgradeStat(HeresyCore.Entities.Token token, string charId, HeresyCore.Entities.Enums.ECharacterStat stat, int points) {
            return base.Channel.UpgradeStat(token, charId, stat, points);
        }
        
        public System.Threading.Tasks.Task<bool> UpgradeStatAsync(HeresyCore.Entities.Token token, string charId, HeresyCore.Entities.Enums.ECharacterStat stat, int points) {
            return base.Channel.UpgradeStatAsync(token, charId, stat, points);
        }
    }
}
